- key:               cpu-mainnet
  name:              CPUchain Mainnet
  client:            cpuchain                             # API client name.
  server:            http://user:password@127.0.0.1:19707 # Public CPUchain node endpoint.
  height:            50000                                # Initial block number from which sync will be started.
  min_confirmations: 6                                    # Minimal confirmations needed for withdraw and deposit confirmation.
  explorer:
    address:         https://explorer.cpuchain.org/address/#{address}
    transaction:     https://explorer.cpuchain.org/tx/#{txid}
  status:            active
