- name:             CPUchain Deposit Wallet
  blockchain_key:   cpu-mainnet
  currency_id:      cpu
  # Address where deposits will be collected to.
  address:          'CWWkTPkNRdpTDSfPw7gxUt9cEaC5PSsP3Y'  # IMPORTANT: Always wrap this value in quotes!
  kind:             deposit    # Wallet kind (deposit, hot, warm, cold or fee).
  nsig:             1          # Number of signatures required for performing withdraw.
  max_balance:      0.0
  status:           active
  gateway:          cpuchaind  # Gateway client name.
  settings:
    #
    # CPUchaind gateway client settings.
    uri:          http://user:password@127.0.0.1:19707

- name:             CPUchain Hot Wallet
  blockchain_key:   cpu-mainnet
  currency_id:      cpu
  # Address where deposits will be collected to.
  address:          'CWWkTPkNRdpTDSfPw7gxUt9cEaC5PSsP3Y'  # IMPORTANT: Always wrap this value in quotes!
  kind:             hot     # Wallet kind (deposit, hot, warm, cold or fee).
  nsig:             1       # Number of signatures required for performing withdraw.
  max_balance:      5.0
  status:           active
  gateway:          cpuchaind   # Gateway client name.
  settings:
    #
    # CPUchaind gateway client settings.
    uri:          http://user:password@127.0.0.1:19707

- name:             CPUchain Warm Wallet
  blockchain_key:   cpu-mainnet
  currency_id:      cpu
  # Address where deposits will be collected to.
  address:          'CWWkTPkNRdpTDSfPw7gxUt9cEaC5PSsP3Y'  # IMPORTANT: Always wrap this value in quotes!
  kind:             warm    # Wallet kind (deposit, hot, warm, cold or fee).
  nsig:             1       # Number of signatures required for performing withdraw.
  max_balance:      50.0
  status:           active
  gateway:          cpuchaind   # Gateway client name.
  settings:
    #
    # CPUchaind gateway client settings.
    uri:          http://user:password@127.0.0.1:19707
